### ISSUE TITLE
Criação de um Readme

### ISSUE THREAD

**Issue by arthurs159** [igor-aguiar/PseudoBank#1]
Oi Igor, olhando seu projeto, percebi que está faltando o readme e ele é o primeiro contato com o projeto que qualquer pessoa vai ter, e muitas vezes o recrutador nem sabe codar, então ele não irá baixar seu projeto para testar. Isso faz o readme mais importante ainda. Eu recomendo colocar um briefing do projeto, quais foram os seus objetivos ao fazer esse projeto, porque decidiu fazer ele, uma fotos de como ficou o resultado, e pelo menos 3 coisas que aprendeu ao fazer esse projeto.

Qualquer dúvida só me chamar!! : )

**Comment by igor-aguiar** [comment]
Olá Arthur, fiz as alterações em que você recomendou, espero que tenha ficado de fácil compreensão. Agradeço o feedbakc.
